"""Structured output schema for the chat assistant (PLAN.md §9).

This is the exact shape the LLM is asked to respond with, passed to LiteLLM
as `response_format`. `trades` and `watchlist_changes` default to empty lists
rather than `None` so downstream code (route handler, mock) never has to
distinguish "omitted" from "empty".
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


class TradeAction(BaseModel):
    ticker: str
    side: Literal["buy", "sell"]
    quantity: float


class WatchlistChangeAction(BaseModel):
    ticker: str
    action: Literal["add", "remove"]


class ChatCompletionResult(BaseModel):
    """Legacy single-call shape (message + trades + watchlist_changes). No
    longer used for the real LLM call path (see `ActionsResult` below) — the
    conversational reply is now a separate streamed call with no structured
    schema at all. Kept because `mock.py` still returns this shape as a
    single source of truth for deterministic mock content; the real chat
    route pulls `.message`/`.trades`/`.watchlist_changes` off of it."""

    message: str
    trades: list[TradeAction] = Field(default_factory=list)
    watchlist_changes: list[WatchlistChangeAction] = Field(default_factory=list)


class ActionsResult(BaseModel):
    """Structured output schema for the actions-only LLM call. The
    conversational reply is generated by a separate, unstructured streaming
    call (`client.stream_chat_message`), so there's no `message` field here
    — just what to auto-execute, if anything."""

    trades: list[TradeAction] = Field(default_factory=list)
    watchlist_changes: list[WatchlistChangeAction] = Field(default_factory=list)
